/**
 * Suchbegriffe für Google News (Profi-Straßenrad) — OR-verknüpft, in Batches.
 * Umlaute/Devisen: wie von dir geliefert (Google normalisiert teils selbst).
 */
export const SPORT_RENNRAD_SCHLUESSELWOERTER: readonly string[] = [
  'Alpecin–Premier Tech',
  'Team Bahrain Victorious',
  'Decathlon–AG2R La Mondiale',
  'EF Education–EasyPost',
  'Groupama–FDJ United',
  'Ineos Grenadiers',
  'Lidl–Trek',
  'Lotto–Intermarché',
  'Movistar Team',
  'NSN Cycling Team',
  'Red Bull–Bora–Hansgrohe',
  'Soudal–Quick-Step',
  'Team Jayco–AlUla',
  'Team Picnic–PostNL',
  'Visma–Lease a Bike',
  'UAE Team Emirates XRG',
  'Uno-X Mobility',
  'XDS Astana Team',
  'Bardiani–CSF 7 Saber',
  'Burgos Burpellet BH',
  'Caja Rural–Seguros RGA',
  'Cofidis',
  'Equipo Kern Pharma',
  'Euskaltel–Euskadi',
  'MBH Bank CSB Telecom Fort',
  'Modern Adventure Pro Cycling',
  'Pinarello–Q36.5 Pro Cycling Team',
  'Solution Tech NIPPO Rali',
  'Team Flanders–Baloise',
  'Team Novo Nordisk',
  'Team Polti VisitMalta',
  'Team TotalEnergies',
  'Tudor Pro Cycling Team',
  'Unibet Rose Rockets',
  'Tour de France',
  "Giro d'Italia",
  'Vuelta a España',
  'Mailand–Sanremo',
  'Flandern-Rundfahrt',
  'Paris–Roubaix',
  'Lüttich–Bastogne–Lüttich',
  'Il Lombardia',
  'Tour Down Under',
  'UAE Tour',
  'Paris–Nizza',
  'Tirreno–Adriatico',
  'Volta a Catalunya',
  'Baskenland-Rundfahrt',
  'Tour de Romandie',
  'Critérium du Dauphiné',
  'Tour de Suisse',
  'Tour de Pologne',
  'Renewi Tour',
  'Tour of Guangxi',
  'Cadel Evans Road Race',
  'Omloop Het Nieuwsblad',
  'Strade Bianche',
  'Brugge-De Panne',
  'E3 Saxo Classic',
  'Gent–Wevelgem',
  'Dwars door Vlaanderen',
  'Amstel Gold Race',
  'La Flèche Wallonne',
  'Eschborn–Frankfurt',
  'San Sebastián Classic',
  'BEMER Cyclassics',
  'Bretagne Classic',
  'GP de Québec',
  'GP de Montréal',
  'Kuurne–Brüssel–Kuurne',
  'Trofeo Laigueglia',
  'Milano–Torino',
  'Nokere Koerse',
  'GP de Denain',
  'Scheldeprijs',
  'Brabantse Pijl',
  'Tro-Bro Léon',
  'Brussels Cycling Classic',
  'AlUla Tour',
  'Valencia-Rundfahrt',
  'Tour of Oman',
  'Algarve-Rundfahrt',
  'Ruta del Sol',
  'Tour of the Alps',
  'Tour of Norway',
  'Tour of Belgium',
  'Tour of Slovenia',
  'Deutschland Tour',
  'Tour of Britain',
  'Rund um Köln',
  'Le Samyn',
  "Giro dell'Appennino",
  'Grand Prix de Wallonie',
  'Paris–Bourges',
  'Trofeo Serra de Tramuntana',
  'Veenendaal–Veenendaal',
  'Japan Cup',
  'Lotto Famenne Ardenne Classic',
  'Muscat Classic',
  'Classic Var',
  'Clásica de Almería',
  'Figueira Champions Classic',
  'Classic Loire Atlantique',
  'Cholet Agglo Tour',
  'La Roue Tourangelle',
  'Route Adélie de Vitré',
  'Paris–Camembert',
] as const
